spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: security-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
        - id: departments
          uri: http://localhost:8084
          predicates:
            - Path=/departments/**
          filters:
            - DepartmentsServiceFilter
        - id: deadlines
          uri: http://localhost:8082
          predicates:
            - Path=/deadline/department
            - Path=/deadline/all
          filters:
            - name: DeadlinesServiceFilter
              path: /deadline/department
            - name: DeadlinesServiceFilter
              path: /deadline/all
        - id: request-receiver
          uri: http://localhost:8083
          predicates:
            - Path=/request/**

  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
eureka:
  client:
    register-with-eureka: false
logging:
  level:
    com: DEBUG
server:
  port: 8086
application:
  config:
    security-service:
      url: http://localhost:8085/auth